name: Build & Deploy to Zone
on:
  push:
    branches:
      - main
      - beta
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '26'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload built files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'beta' }}
      url: ${{ github.ref_name == 'main' && 'https://orbit.tanelneitov.eu' || 'https://beta-orbit.tanelneitov.eu' }}
    steps:
      - name: Download built files
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Connect to server over SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST_SERVER_IP }} >> ~/.ssh/known_hosts
          
      - name: Set deploy path
        id: vars
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "path=~/domeenid/www.tanelneitov.eu/orbit/" >> "$GITHUB_OUTPUT"
          else
            echo "path=~/domeenid/www.tanelneitov.eu/beta-orbit/" >> "$GITHUB_OUTPUT"
          fi
          
      - name: Deploy built site
        run: |
          rsync -vrm ./dist/ ${{ secrets.SSH_LOGIN_CREDS }}:${{ steps.vars.outputs.path }}